apps/potlock/widget/Components/ListSection.jsx, apps/potlock/widget/Project/Card.jsx, apps/potlock/widget/Project/ListPage.jsx
- Fix alignment, cards with less or more text makes rows un even, either add whitespace or clip for projects
- Project Search Filters: Most donations and least donations
- Project Search: Filter by New -> Old projects (by dated added to potlock registry)
- Add search bar with filters for tags and categories
=> Chore project explorer page

apps/potlock/widget/Components/ListSection.jsx
- Fix card width for mobile
- Add "on bottom" text when has no more project
- fix sort filter unable to click
=> Hot fix card width and sort filter

apps/potlock/widget/Components/ListSection.jsx, apps/potlock/widget/Project/BannerHeader.jsx, apps/potlock/widget/Project/CreateForm.jsx, apps/potlock/widget/Project/ListPage.jsx
- Fix unable to upload profile image
- Fix unable to upload background image
- Add website input field to "social link" section
=> Fix: background image and profile image in "create project" page

apps/potlock/widget/Components/ListSection.jsx, apps/potlock/widget/Components/ProjectCard.jsx, apps/potlock/widget/Project/SeachBar.jsx
change ProjectCard and Searchbar widget url from orasci-contributor.near to potlock.near
=> feat: add ProjectCard and Searchbar components

apps/potlock/widget/Index.jsx
Replace `Submitted` and `InReview` statuses with `Pending` as per latest Registry updates
=> update project statuses

apps/potlock/widget/Index.jsx, apps/potlock/widget/Pots/ConfigForm.jsx, apps/potlock/widget/Pots/Deploy.jsx
Closes https://github.com/PotLock/bos-app/issues/151
=> add sybil resistance option to deploy form

apps/potlock/widget/Index.jsx, apps/potlock/widget/Pots/Card.jsx
Closes https://github.com/PotLock/bos-app/issues/159
=> add spinner when pot card loading

apps/potlock/widget/Components/ListSection.jsx, apps/potlock/widget/Index.jsx, apps/potlock/widget/Pots/Applications.jsx, apps/potlock/widget/Pots/ConfigForm.jsx, apps/potlock/widget/Project/SearchBar.jsx
Closes https://github.com/PotLock/bos-app/issues/155
=> Applications filter & search

apps/potlock/widget/Project/Body.jsx
Closes https://github.com/PotLock/bos-app/issues/202
=> fix edit project button rendering

apps/potlock/widget/Project/Body.jsx, apps/potlock/widget/Project/Detail.jsx
Closes https://github.com/PotLock/bos-app/issues/178
=> add notes for admin review

apps/potlock/widget/Project/Detail.jsx
Closes https://github.com/PotLock/bos-app/issues/183
=> add project status banner

apps/potlock/widget/Pots/ConfigForm.jsx, apps/potlock/widget/Pots/Header.jsx
closes https://github.com/PotLock/bos-app/issues/158
=> check for registry requirement

apps/potlock/widget/Cart/BreakdownSummary.jsx, apps/potlock/widget/Components/DonorsCard.jsx, apps/potlock/widget/Components/DonorsLeaderboard.jsx, apps/potlock/widget/Index.jsx
Closes https://github.com/PotLock/bos-app/issues/219
=> cache near-usd exchange rate

apps/potlock/widget/Profile/Detail.jsx, apps/potlock/widget/Profile/DonationsTable.jsx, apps/potlock/widget/Profile/Tags.jsx, apps/potlock/widget/Project/Detail.jsx, apps/potlock/widget/Project/Options.jsx
- hide attestations on the project
- make donations the default tab on the profile page
- show matched round donations on the profile page
- fix profile tags not showing
- fix donations order in the table
=> Profile page fixes

.github/workflows/deploy-mainnet.yml
RPC workaround has been merged to main, we can reflect here again
=> Set workflow to use main bos-workspace

apps/potlock/widget/Pots/Detail.jsx, apps/potlock/widget/Pots/Sponsors.jsx, apps/potlock/widget/Pots/SponsorsBoard.jsx, apps/potlock/widget/Project/NavOptionsMobile.jsx
=> Pot Sponsors Board

apps/potlock/widget/Cart/Checkout.jsx, apps/potlock/widget/Pots/ConfigForm.jsx, apps/potlock/widget/Profile/Body.jsx, apps/potlock/widget/Project/Actions.jsx, apps/potlock/widget/Project/CreateForm.jsx, apps/potlock/widget/Project/Detail.jsx, apps/potlock/widget/Project/ListPage.jsx, apps/potlock/widget/Project/ModalDonation.jsx
Fix init for PotlockRegistrySDK
=> Fix the red flash "PotlockRegistrySDK is not a function"

apps/potlock/widget/Index.jsx, apps/potlock/widget/Profile/Detail.jsx, apps/potlock/widget/Project/DonationStats.jsx, apps/potlock/widget/Project/ListPage.jsx, apps/potlock/widget/Project/ModalDonation.jsx, apps/potlock/widget/SDK/donate.jsx
=> Adds donate sdk

apps/potlock/widget/Project/Options.jsx, apps/potlock/widget/Project/Pots.jsx
https://github.com/orgs/PotLock/projects/8/views/22?pane=issue&itemId=54510425
=> add pots tab to project page

apps/potlock/widget/Cart/Checkout.jsx, apps/potlock/widget/Index.jsx
Closes https://github.com/PotLock/bos-app/issues/361
- Fixes error after redirecting from transaction containing multiple donations
- Adds sharing multiple donations in tweet
=> fix multiple cart donation errors

apps/potlock/widget/Components/Banner.jsx, apps/potlock/widget/Index.jsx
closes [#338](https://github.com/PotLock/bos-app/issues/338)
=> add live round banner

apps/potlock/widget/Cart/BreakdownSummary.jsx, apps/potlock/widget/Cart/Checkout.jsx, apps/potlock/widget/Cart/CheckoutBreakdown.jsx, apps/potlock/widget/Cart/CheckoutItem.jsx, apps/potlock/widget/Index.jsx, apps/potlock/widget/Profile/Detail.jsx, apps/potlock/widget/Profile/DonationsTable.jsx, apps/potlock/widget/Project/Card.jsx, apps/potlock/widget/Project/DonationsInfo.jsx, apps/potlock/widget/Project/FundingRaised.jsx, apps/potlock/widget/Project/ModalDonation.jsx, apps/potlock/widget/Project/ModalSuccess.jsx, apps/potlock/widget/Project/PotlockFunding.jsx, apps/potlock/widget/SDK/ft.jsx, apps/potlock/widget/utils.jsx
- Add functionality to donate FTs from donate modal (cannot donate FTs from cart yet due to complexity from large number of transactions required)
- Add display of FT donations to UI
=> add ft support

apps/potlock/widget/Project/PotlockFunding.jsx, apps/potlock/widget/SDK/ft.jsx
Resolves ".then is not a function" error
=> remove unnecessary FtSDK

apps/potlock/widget/ModalDonation/ConfirmDirect.jsx, apps/potlock/widget/ModalDonation/Form.jsx, apps/potlock/widget/Pots/DonationsTable.jsx, apps/potlock/widget/Pots/FlagModal.jsx, apps/potlock/widget/Pots/FlagSuccessModal.jsx, apps/potlock/widget/Pots/FlaggedAccounts.jsx, apps/potlock/widget/Pots/Payouts.jsx, apps/potlock/widget/Profile/Tabs.jsx, apps/potlock/widget/SDK/pot.jsx
closes [#530](https://github.com/PotLock/bos-app/issues/530)
EX:
```
{
"name": "Mohamed ElKhamisy",
.
.
.
"pLBlacklistedAccounts": "{\"build.v1.potfactory.potlock.near\":{\"tenkdao.near\":\"teset Flag tenkdao.near\",\"pawaha.near\":\"test  test test\"},\"infra.v1.potfactory.potlock.near\":{\"pawaha.near\":\"test test  test\"}}"
}
```
=> add flag donations to pot

apps/potlock/widget/Components/Donors.jsx, apps/potlock/widget/Components/DonorsTrx.jsx, apps/potlock/widget/Pots/Applications.jsx, apps/potlock/widget/Pots/Sponsors.jsx
- I am not including fn on the leaderboard calculations anymore 
- handled fn tokens on the donations tab
=> fix donor leaderboard calcs

apps/potlock/widget/Components/Banner.jsx, apps/potlock/widget/Components/Header.jsx, apps/potlock/widget/ModalDonation/Banners.jsx, apps/potlock/widget/ModalDonation/Form.jsx, apps/potlock/widget/ModalDonation/FormPot.jsx, apps/potlock/widget/Pots/Detail.jsx, apps/potlock/widget/Pots/FlaggedAccounts.jsx, apps/potlock/widget/Pots/Header.jsx, apps/potlock/widget/Pots/Payouts.jsx, apps/potlock/widget/Pots/PoolAllocationTable.jsx, apps/potlock/widget/Pots/Projects.jsx, apps/potlock/widget/Project/Card.jsx, apps/potlock/widget/Project/ModalSuccess.jsx, apps/potlock/widget/constants.jsx, apps/potlock/widget/utils.jsx
use new `get_human_score_batch` method to get human scores at allocation calculation time. first step towards after-the-fact sybil verification (not blocking users from donating before they pass sybil verification)
=> use `get_human_score_batch`
